// Code generated by cmd/gen_i18n. DO NOT EDIT.
package i18nk

const (
	CleanCacheFailed = "CleanCacheFailed"
	CleaningCache = "CleaningCache"
	GetCacheAbsPathFailed = "GetCacheAbsPathFailed"
	GetWorkdirFailed = "GetWorkdirFailed"
	InvalidCacheDir = "InvalidCacheDir"
	Bye = "bye"
	Exiting = "exiting"
	Initing = "initing"
)
