// Code generated by cmd/gen_i18n. DO NOT EDIT.
package i18nk

const (
	CleanCacheFailed = "CleanCacheFailed"
	CleaningCache = "CleaningCache"
	ConfigInvalidDuplicateStorageName = "ConfigInvalid.DuplicateStorageName"
	ConfigInvalidWorkersOrRetry = "ConfigInvalid.WorkersOrRetry"
	CreateRmTimerFailed = "CreateRmTimerFailed"
	GetCacheAbsPathFailed = "GetCacheAbsPathFailed"
	GetWorkdirFailed = "GetWorkdirFailed"
	InvalidCacheDir = "InvalidCacheDir"
	LoadedStorages = "LoadedStorages"
	RemoveFileAfter = "RemoveFileAfter"
	RemoveFileFailed = "RemoveFileFailed"
	Bye = "bye"
	Exiting = "exiting"
	Initing = "initing"
)
