// Code generated by cmd/geni18n. DO NOT EDIT.
package i18nk

type Key string

const (
	BotMsgHelpTextFmt Key = "bot.msg.help_text_fmt"
	BotMsgSaveHelpText Key = "bot.msg.save_help_text"
	BotMsgWatchHelpText Key = "bot.msg.watch_help_text"
	ConfigErrDuplicateStorageName Key = "config.err.duplicate_storage_name"
	ConfigErrInvalidCacheDir Key = "config.err.invalid_cache_dir"
	ConfigLoadedStorages Key = "config.loaded_storages"
	ErrCleanCacheFailed Key = "err.clean_cache_failed"
	ErrGetCacheAbsPathFailed Key = "err.get_cache_abs_path_failed"
	ErrGetWorkdirFailed Key = "err.get_workdir_failed"
	LifetimeBye Key = "lifetime.bye"
	LifetimeCleaningCache Key = "lifetime.cleaning_cache"
	LifetimeExiting Key = "lifetime.exiting"
	LifetimeInitfailed Key = "lifetime.initfailed"
	LifetimeIniting Key = "lifetime.initing"
	LifetimeUserLoginFailed Key = "lifetime.user_login_failed"
	ParserPluginLoadFailed Key = "parser.plugin.load_failed"
	ParserPluginLoadedDir Key = "parser.plugin.loaded_dir"
)
