name: Docker Build

on:
  workflow_dispatch:
  push:
    branches: # 仅 main 分支
      - main
    #tags: # 仅带 tag:v* 时构建
      #- v*
  #pull_request:
    #types: [closed]
    #branches:
      #- main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: cosrbackup/saveany-bot:latest
        #build-args: |           #传递构建参数
          #VERSION=1.3.1
